# Generated by Django 5.0 on 2024-01-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.CharField(blank=True, max_length=20, null=True)),
                ('linkgithub', models.CharField(blank=True, max_length=100, null=True)),
                ('linkdeploy', models.CharField(blank=True, max_length=100, null=True)),
                ('datainfo', models.CharField(blank=True, max_length=30, null=True)),
                ('section', models.CharField(choices=[('1', 'expirience'), ('2', 'Curriculum'), ('3', 'Services'), ('4', 'Portfolio')], max_length=1)),
                ('cover', models.ImageField(blank=True, upload_to='portifolio/projects/cover/')),
            ],
        ),
    ]
